- hosts: localhost
  become: true
  tasks:
    - name: Install gcc
      apt: name=build-essential
    - name: Download neovim deb package
      get_url: 
        url="https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb"
        dest="~/nvim-linux64.deb"
    - name: Install neovim
      apt: deb="~/nvim-linux64.deb"
    - name: Remove neovim.deb file
      ansible.builtin.file:
        path: ~/nvim-linux64.deb
        state: absent
    - name: Install zsh
      apt: name=zsh
    - name: Change shell
      shell: chsh -s `which zsh`
    - name: Install ohmyzsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    - name: Install Antigen plugin manager for zsh
      shell: curl -L git.io/antigen > antigen.zsh
    - name: Install Tmux
      apt: name=tmux
    - name: Create Shell script
      copy:
        dest: ~/dotfiles.sh
        content: |
          git clone --bare https://github.com/C-Rmoser/dotfiles $HOME/.cfg
          function config {
             /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME $@
          }
          mkdir -p .config-backup
          config checkout
          if [ $? = 0 ]; then
            echo "Checked out config.";
            else
              echo "Backing up pre-existing dot files.";
              config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} mv {} .config-backup/{}
          fi;
          config checkout
          config config status.showUntrackedFiles no
    - name: Configure dotfiles
      shell: sh ~/dotfiles.sh
