- hosts: localhost
  become: true
  tasks:
    - name: Install curl
      apt: name=curl
    - name: install git
      apt: name=git-all
    - name: Download neovim deb package
      get_url: 
        url="https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb"
        dest="~/nvim-linux64.deb"
    - name: Install neovim
      apt: deb="~/nvim-linux64.deb"
    - name: Remove neovim.deb file
      ansible.builtin.file:
        path: ~/nvim-linux64.deb
        state: absent
    - name: Install zsh
      apt: name=zsh
    - name: Change shell
      shell: chsh -s `which zsh`
    - name: Install ohmyzsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    - name: Install Antigen plugin manager for zsh
      shell: curl -L git.io/antigen > antigen.zsh
    - name: Install Tmux
      apt: name=tmux
    - name: Clone dotfiles repo
      git:
        repo: https://github.com/C-Rmoser/dotfiles
        dest: ~/.cfg
        bare: true
    - name: Backup dotfiles
      shell: mkdir -p .config-backup && \ /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | \ xargs -I{} mv {} .config-backup/{}
    - name: Checkout dotfiles
      shell: /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME checkout
    - name: Set showuntrackedfiles to no
      shell: /usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME config --local status.showUntrackedFiles no
